name: bicep-validate
on:
  push:
    branches: [ "main" ]
  pull_request:
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5
      - uses: azure/bicep-build-action@v1
        with:
          files: |
            **/*.bicep
