
name: Validate Bicep
on: [push, pull_request]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Install Azure CLI + Bicep
        run: |
          curl -sL https://aka.ms/InstallAzureCLIDeb | sudo bash
          az bicep install
      - name: Build all bicep
        run: |
          find . -name '*.bicep' -print -exec az bicep build --file {} \;
